bottles_locations:
  - {xyz: "-0.2 0.4 0", rpy: "0 0 0"}
  - {xyz: "-0.2 0.5 0", rpy: "0 0 0"}
  - {xyz: "-0.2 0.6 0", rpy: "0 0 0"}
  - {xyz: "-0.3 0.4 0", rpy: "0 0 0"}
  - {xyz: "-0.3 0.5 0", rpy: "0 0 0"}
  - {xyz: "-0.3 0.6 0", rpy: "0 0 0"}
n_bottles: 6
