bottles_locations:
  - {xyz: "0.1 0.05 0.05", rpy: "0 0 0"}
  - {xyz: "0.2 0.05 0.05", rpy: "0 0 0"}
  - {xyz: "0.3 0.05 0.05", rpy: "0 0 0"}
  - {xyz: "0.1 0.15 0.05", rpy: "0 0 0"}
  - {xyz: "0.2 0.15 0.05", rpy: "0 0 0"}
  - {xyz: "0.3 0.15 0.05", rpy: "0 0 0"}
n_bottles: 6
