goal:
  - pick_robot_box_1:
      task_name: pick_robot_box
      required_agents: []
      precedence_constraints: []
  - pick_robot_box_2:
      task_name: pick_robot_box
      required_agents: []
      precedence_constraints: []
  - pick_robot_box_3:
      task_name: pick_robot_box
      required_agents: []
      precedence_constraints: []
  - pick_robot_box_4:
      task_name: pick_robot_box
      required_agents: []
      precedence_constraints: []

  - place_robot_box_1:
      task_name: place_robot_box
      required_agents: []
      precedence_constraints: [pick_robot_box_1]
  - place_robot_box_2:
      task_name: place_robot_box
      required_agents: []
      precedence_constraints: [pick_robot_box_2]
  - place_robot_box_3:
      task_name: place_robot_box
      required_agents: []
      precedence_constraints: [pick_robot_box_3]
  - place_robot_box_4:
      task_name: place_robot_box
      required_agents: []
      precedence_constraints: [pick_robot_box_4]
