goal:
  - board_localization:
      task_name: board_localization
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []
  - probe:
      task_name: probe
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: ["board_localization"]
  - remove_plug:
      task_name: remove_plug
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: ["board_localization"]
  - battery_sorting_1:
      task_name: battery_sorting
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []
  - battery_sorting_2:
      task_name: battery_sorting
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []


  - remove_notebook_cover:
      task_name: remove_notebook_cover
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []
  - remove_notebook_components:
      task_name: remove_notebook_components
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: ["remove_notebook_cover"]
  - disassemble_remote_control_1:
      task_name: disassemble_remote_control
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []
  - disassemble_remote_control_2:
      task_name: disassemble_remote_control
      required_agents: []
      precedence_constraints: []
      soft_precedence_constraints: []
